# Generated by Django 5.2.16 on 2026-08-04 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=250)),
                ('problem_statement', models.TextField()),
                ('proposed_solution', models.TextField()),
                ('stage', models.CharField(choices=[('idea', 'Idea Stage'), ('prototype', 'Prototype / MVP'), ('seed', 'Pre-Seed / Seed'), ('growth', 'Early Growth'), ('expansion', 'Expansion / Scaling')], default='idea', max_length=20)),
                ('category', models.CharField(choices=[('tech', 'Technology & Software'), ('health', 'Healthcare & MedTech'), ('finance', 'FinTech'), ('edu', 'EdTech'), ('ecommerce', 'E-Commerce & Retail'), ('other', 'Other')], default='other', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='startup_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('founder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
