# Generated by Django 5.2.16 on 2026-08-16 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0002_idea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='problem_statement',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='proposed_solution',
        ),
        migrations.AddField(
            model_name='idea',
            name='problem_statement',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='proposed_solution',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='incubator.startup'),
        ),
        migrations.AddField(
            model_name='idea',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
