# Generated by Django 5.2.16 on 2026-08-16 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0003_remove_startup_problem_statement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='incubator.startup'),
        ),
    ]
