# Generated by Django 5.2.16 on 2026-09-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0005_startup_mentor_feedback_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='under_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='incubation_status',
            field=models.CharField(choices=[('idea_stage', 'Idea Stage'), ('under_review', 'Under Review'), ('incubating', 'Incubating'), ('active', 'Active'), ('completed', 'Completed')], default='idea_stage', max_length=20),
        ),
    ]
