# Generated by Django 5.2.16 on 2026-09-02 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0006_idea_under_review_at_startup_incubation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('startup_registered', 'Startup Registered'), ('mentor_assigned', 'Mentor Assigned'), ('mentor_changed', 'Mentor Changed'), ('mentor_removed', 'Mentor Removed'), ('status_changed', 'Status Changed'), ('idea_submitted', 'Idea Submitted'), ('idea_under_review', 'Idea Under Review'), ('feedback_added', 'Feedback Added'), ('milestone_created', 'Milestone Created'), ('milestone_updated', 'Milestone Updated'), ('milestone_completed', 'Milestone Completed')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='incubator.startup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
