# Generated by Django 5.2.16 on 2026-09-03 10:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0008_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('startup_registered', 'Startup Registered'), ('mentor_assigned', 'Mentor Assigned'), ('mentor_changed', 'Mentor Changed'), ('mentor_removed', 'Mentor Removed'), ('status_changed', 'Status Changed'), ('idea_submitted', 'Idea Submitted'), ('idea_under_review', 'Idea Under Review'), ('feedback_added', 'Feedback Added'), ('milestone_created', 'Milestone Created'), ('milestone_updated', 'Milestone Updated'), ('milestone_completed', 'Milestone Completed'), ('team_member_added', 'Team Member Added'), ('pending_invitation_created', 'Pending Invitation Created'), ('team_member_removed', 'Team Member Removed'), ('team_member_updated', 'Team Member Updated'), ('document_uploaded', 'Document Uploaded'), ('document_deleted', 'Document Deleted'), ('document_updated', 'Document Updated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mentor_assigned', 'Mentor Assigned'), ('mentor_changed', 'Mentor Changed'), ('startup_status_changed', 'Startup Status Changed'), ('idea_submitted', 'Idea Submitted'), ('idea_under_review', 'Idea Under Review'), ('feedback_received', 'Feedback Received'), ('milestone_created', 'Milestone Created'), ('milestone_completed', 'Milestone Completed'), ('team_member_added', 'Team Member Added'), ('document_uploaded', 'Document Uploaded')], max_length=50),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('pitch_deck', 'Pitch Deck'), ('business_plan', 'Business Plan'), ('financial', 'Financial Document'), ('product', 'Product Document'), ('legal', 'Legal Document'), ('market_research', 'Market Research'), ('other', 'Other')], default='other', max_length=50)),
                ('file', models.FileField(upload_to='startup_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='incubator.startup')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('position', models.CharField(choices=[('founder', 'Founder'), ('cofounder', 'Co-Founder'), ('cto', 'CTO'), ('ceo', 'CEO'), ('coo', 'COO'), ('developer', 'Developer'), ('designer', 'Designer'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('other', 'Other')], default='other', max_length=50)),
                ('custom_position', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='incubator.startup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startup_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
