# Generated by Django 5.2.16 on 2026-09-04 15:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0009_alter_activity_activity_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('startup_registered', 'Startup Registered'), ('mentor_assigned', 'Mentor Assigned'), ('mentor_changed', 'Mentor Changed'), ('mentor_removed', 'Mentor Removed'), ('status_changed', 'Status Changed'), ('idea_submitted', 'Idea Submitted'), ('idea_under_review', 'Idea Under Review'), ('feedback_added', 'Feedback Added'), ('milestone_created', 'Milestone Created'), ('milestone_updated', 'Milestone Updated'), ('milestone_completed', 'Milestone Completed'), ('team_member_added', 'Team Member Added'), ('pending_invitation_created', 'Pending Invitation Created'), ('team_member_removed', 'Team Member Removed'), ('team_member_updated', 'Team Member Updated'), ('document_uploaded', 'Document Uploaded'), ('evaluation_received', 'Evaluation Received'), ('document_deleted', 'Document Deleted'), ('document_updated', 'Document Updated'), ('evaluation_created', 'Evaluation Created'), ('evaluation_updated', 'Evaluation Updated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mentor_assigned', 'Mentor Assigned'), ('mentor_changed', 'Mentor Changed'), ('startup_status_changed', 'Startup Status Changed'), ('idea_submitted', 'Idea Submitted'), ('idea_under_review', 'Idea Under Review'), ('feedback_received', 'Feedback Received'), ('milestone_created', 'Milestone Created'), ('milestone_completed', 'Milestone Completed'), ('team_member_added', 'Team Member Added'), ('document_uploaded', 'Document Uploaded'), ('evaluation_received', 'Evaluation Received')], max_length=50),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovation_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('market_potential_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('business_model_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('team_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('execution_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='incubator.startup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('startup', 'evaluator'), name='unique_evaluation')],
            },
        ),
    ]
