# Generated by Django 5.2.16 on 2026-09-10 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0010_alter_activity_activity_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('startup_registered', 'Startup Registered'), ('mentor_assigned', 'Mentor Assigned'), ('mentor_changed', 'Mentor Changed'), ('mentor_removed', 'Mentor Removed'), ('status_changed', 'Status Changed'), ('idea_submitted', 'Idea Submitted'), ('idea_under_review', 'Idea Under Review'), ('feedback_added', 'Feedback Added'), ('milestone_created', 'Milestone Created'), ('milestone_updated', 'Milestone Updated'), ('milestone_completed', 'Milestone Completed'), ('team_member_added', 'Team Member Added'), ('pending_invitation_created', 'Pending Invitation Created'), ('team_member_removed', 'Team Member Removed'), ('team_member_updated', 'Team Member Updated'), ('document_uploaded', 'Document Uploaded'), ('evaluation_received', 'Evaluation Received'), ('document_deleted', 'Document Deleted'), ('document_updated', 'Document Updated'), ('evaluation_created', 'Evaluation Created'), ('evaluation_updated', 'Evaluation Updated'), ('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('event_cancelled', 'Event Cancelled'), ('event_registered', 'Event Registered'), ('event_unregistered', 'Event Unregistered'), ('attendance_marked', 'Attendance Marked'), ('collaboration_request_sent', 'Collaboration Request Sent'), ('collaboration_request_accepted', 'Collaboration Request Accepted'), ('collaboration_request_rejected', 'Collaboration Request Rejected'), ('collaboration_request_cancelled', 'Collaboration Request Cancelled')], max_length=50),
        ),
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('request_type', models.CharField(choices=[('startup_collaboration', 'Startup Collaboration'), ('mentorship', 'Mentorship'), ('networking', 'Networking'), ('partnership', 'Partnership'), ('project', 'Project'), ('other', 'Other')], default='networking', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_collaboration_requests', to=settings.AUTH_USER_MODEL)),
                ('recipient_startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_collaboration_requests', to='incubator.startup')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_collaboration_requests', to=settings.AUTH_USER_MODEL)),
                ('requester_startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_collaboration_requests', to='incubator.startup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('workshop', 'Workshop'), ('mentoring', 'Mentoring Session'), ('pitch', 'Pitch Event'), ('investor_meet', 'Investor Meet'), ('networking', 'Networking Event'), ('incubation', 'Incubation Session'), ('seminar', 'Entrepreneurship Seminar'), ('demo_day', 'Demo Day'), ('other', 'Other')], default='workshop', max_length=50)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='incubator.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'participant'), name='unique_event_participation')],
            },
        ),
    ]
