# Generated by Django 5.2.16 on 2026-09-17 17:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0011_alter_activity_activity_type_collaborationrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('startup_registered', 'Startup Registered'), ('mentor_assigned', 'Mentor Assigned'), ('mentor_changed', 'Mentor Changed'), ('mentor_removed', 'Mentor Removed'), ('status_changed', 'Status Changed'), ('idea_submitted', 'Idea Submitted'), ('idea_under_review', 'Idea Under Review'), ('feedback_added', 'Feedback Added'), ('milestone_created', 'Milestone Created'), ('milestone_updated', 'Milestone Updated'), ('milestone_completed', 'Milestone Completed'), ('team_member_added', 'Team Member Added'), ('pending_invitation_created', 'Pending Invitation Created'), ('team_member_removed', 'Team Member Removed'), ('team_member_updated', 'Team Member Updated'), ('document_uploaded', 'Document Uploaded'), ('evaluation_received', 'Evaluation Received'), ('document_deleted', 'Document Deleted'), ('document_updated', 'Document Updated'), ('evaluation_created', 'Evaluation Created'), ('evaluation_updated', 'Evaluation Updated'), ('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('event_cancelled', 'Event Cancelled'), ('event_registered', 'Event Registered'), ('event_unregistered', 'Event Unregistered'), ('attendance_marked', 'Attendance Marked'), ('collaboration_request_sent', 'Collaboration Request Sent'), ('collaboration_request_accepted', 'Collaboration Request Accepted'), ('collaboration_request_rejected', 'Collaboration Request Rejected'), ('collaboration_request_cancelled', 'Collaboration Request Cancelled'), ('funding_round_created', 'Funding Round Created'), ('funding_round_opened', 'Funding Round Opened'), ('funding_round_closed', 'Funding Round Closed'), ('funding_application_submitted', 'Funding Application Submitted'), ('funding_application_status_changed', 'Funding Application Status Changed'), ('investor_meeting_scheduled', 'Investor Meeting Scheduled'), ('job_posting_created', 'Job Posting Created'), ('job_published', 'Job Published'), ('job_closed', 'Job Closed'), ('job_application_submitted', 'Job Application Submitted'), ('job_application_shortlisted', 'Job Application Shortlisted'), ('job_application_rejected', 'Job Application Rejected'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('pitch_deck_uploaded', 'Pitch Deck Uploaded'), ('pitch_deck_updated', 'Pitch Deck Updated')], max_length=50),
        ),
        migrations.CreateModel(
            name='FundingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=200)),
                ('round_type', models.CharField(choices=[('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('bridge', 'Bridge'), ('other', 'Other')], default='seed', max_length=50)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('raised_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('equity_offered', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('opening_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rounds', to='incubator.startup')),
            ],
        ),
        migrations.CreateModel(
            name='FundingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_applications', to=settings.AUTH_USER_MODEL)),
                ('funding_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='incubator.fundinground')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=60, help_text='Duration in minutes')),
                ('meeting_type', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person')], default='online', max_length=20)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funding_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='incubator.fundingapplication')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_investor_meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_type', models.CharField(choices=[('angel', 'Angel Investor'), ('vc', 'Venture Capital'), ('corporate', 'Corporate Investor'), ('seed', 'Seed Fund'), ('accelerator', 'Accelerator'), ('other', 'Other')], default='angel', max_length=50)),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('investment_focus', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_industries', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_startup_stages', models.CharField(blank=True, max_length=255, null=True)),
                ('min_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('hired', 'Hired'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=60, help_text='Duration in minutes')),
                ('meeting_type', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person')], default='online', max_length=20)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='incubator.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('requirements', models.TextField()),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract'), ('freelance', 'Freelance')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('junior', 'Junior'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead/Manager')], default='entry', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='incubator.startup')),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='incubator.jobposting'),
        ),
        migrations.AddConstraint(
            model_name='fundingapplication',
            constraint=models.UniqueConstraint(fields=('funding_round', 'investor'), name='unique_funding_application'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('job', 'applicant'), name='unique_job_application'),
        ),
    ]
